apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: ace-server-deploy
spec:
  params:
    - name: project
      description: Specify the name of the project being built.
      default: cp4iivt
    - name: buildversion
      description: Docker image version for the BAR file
      default: ""
    - name: env
      default: "dev"
      description: Specfiy the current environment. It is used in computing the Helm release name.
    - name: production
      default: "false"
      description: Specifies if the deployment is production-like with High Availability enabled. Default [false]
  resources:
    - name: source
      type: git
    - name: image
      type: image
  tasks:
  - name: generate-bar
    resources:
      inputs:
      - name: source
        resource: source
    params:
      - name: project
        value: $(params.project)
    taskRef:
      name: generate-bar 
  - name: build-image
    resources:
      inputs:
      - name: source
        resource: source
      outputs:
      - name: image
        resource: image
    params:
      - name: buildversion
        value: $(params.buildversion)
      - name: dockerfileLocation
        value: ./workspace/$(params.project)/Dockerfile
    taskRef:
      name: build-bar
    runAfter:
    - generate-bar   
  - name: install-ace-server
    taskRef:
      name: install-ace-server
    params:
    - name: production
      value: $(params.production)
    - name: env
      value: $(params.env)
    - name: integrationComponent
      value: ace-server
    - name: project
      value: $(params.project)
    - name: buildversion
      value: $(params.buildversion)
    resources:
      inputs:
      - name: source
        resource: source
      - name: image
        resource: image
    runAfter:
    - build-image