apiVersion: v1
items:
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: build-image-cp4iivt
  spec:
    params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/ace/cp4iivt
    type: image
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: cp4i-ace-server-source
  spec:
    params:
    - name: url
      value: https://github.ibm.com/rsundara/cp4i-ace-server
    type: git
kind: List
