apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: install-ace-server
spec:
  params:
    - name: project
      description: Specify the name of the project being built.
      default: cp4iivt
    - name: buildversion
      description: Docker image version for the BAR file
      default: ""
    - name: env
      default: "dev"
      description: Specfiy the current environment. It is used in computing the Helm release name.
      description: File storage class
    - name: production
      default: "false"
      description: Specifies if the deployment is production-like with High Availability enabled. Default [false]
      
  resources:
    - name: source
      type: git
    - name: image
      type: image
      
  tasks:
  - name: install-ace-server
    taskRef:
      name: install-ace-server
    params:
    - name: production
      value: $(params.production)
    - name: env
      value: $(params.env)
    - name: integrationComponent
      value: ace-server
    - name: project
      value: $(params.project)
    - name: buildversion
      value: $(params.buildversion)
    resources:
      inputs:
      - name: source
        resource: source
      - name: image
        resource: image